services:
  app:
    image: amadeu123/blog-backend
    ports:
     - "${PORT:-3000}:3000"
    environment:
     - PORT=${PORT:-3000}
     - JWT_SECRET=${JWT_SECRET:-my_super_secret_key}

    env_file:
      - .env
    restart: always
